import * as XLSX from 'xlsx';
import { tursoBatch, tursoSelect } from './turso';

type Spec={key:string;target:string;kind:'team'|'lead'|'opp'|'call'|'ticket';sheetIncludes:string;required:string[]};
const SPECS:Spec[]=[
 {key:'تیم مشاورین',target:'team_members',kind:'team',sheetIncludes:'لیست کامل واحد',required:['نام و نام خانوادگی','کد پرسنلی','ایمیل شرکتی','تیم لید','تیم','جنسیت','رده','واحد تجاری']},
 {key:'کل باز روزانه',target:'open_leads',kind:'lead',sheetIncludes:'سرنخ های باز روزانه',required:['شماره سرنخ','تاریخ ثبت','آخرین وضعیت','مالک','نوع سرنخ']},
 {key:'سرنخ های دیروز',target:'daily_leads',kind:'lead',sheetIncludes:'آمار تماس های بسته شده',required:['شماره سرنخ','تاریخ ثبت','تاریخ آخرین تغییر','آخرین وضعیت','مالک']},
 {key:'سرنخ های هفته',target:'weekly_leads',kind:'lead',sheetIncludes:'آمار تماس های بسته شده',required:['شماره سرنخ','تاریخ ثبت','تاریخ آخرین تغییر','آخرین وضعیت','مالک']},
 {key:'سرنخ های ماه',target:'monthly_leads',kind:'lead',sheetIncludes:'آمار تماس های بسته شده',required:['شماره سرنخ','تاریخ ثبت','تاریخ آخرین تغییر','آخرین وضعیت','مالک']},
 {key:'فرصت های دیروز',target:'daily_opportunities',kind:'opp',sheetIncludes:'فرصت های دیروز',required:['عنوان','تاریخ ثبت','وضعیت','ثبت کننده','مالک']},
 {key:'فرصت های هفته ی گذشته',target:'weekly_opportunities',kind:'opp',sheetIncludes:'فرصت های هفته',required:['عنوان','تاریخ ثبت','وضعیت','ثبت کننده','مالک']},
 {key:'فرصت های ماه گذشته',target:'monthly_opportunities',kind:'opp',sheetIncludes:'فرصت های ماه',required:['عنوان','تاریخ ثبت','وضعیت','ثبت کننده','مالک']},
 {key:'کل تماس های دیروز',target:'daily_calls',kind:'call',sheetIncludes:'آمار روزانه تماس',required:['Subject','کاربر','صف تماس','Actual Start']},
 {key:'کل تماس های هفته',target:'weekly_calls',kind:'call',sheetIncludes:'آمار هفتگی تماس',required:['Subject','کاربر','صف تماس','Actual Start']},
 {key:'کل تماس های ماه',target:'monthly_calls',kind:'call',sheetIncludes:'آمار ماهانه تماس',required:['Subject','کاربر','صف تماس','Actual Start']},
 {key:'تیکت روزانه',target:'daily_tickets',kind:'ticket',sheetIncludes:'All Asset management-yesterday',required:['Owner (Object) (Case)','موضوع تماس (Object) (Case)','علت وضعیت (Object) (Case)']},
 {key:'تیکت هفتگی',target:'weekly_tickets',kind:'ticket',sheetIncludes:'All Asset management-weekly',required:['Owner (Object) (Case)','موضوع تماس (Object) (Case)','علت وضعیت (Object) (Case)']},
 {key:'تیکت ماهانه',target:'monthly_tickets',kind:'ticket',sheetIncludes:'All Asset management-monthly',required:['Owner (Object) (Case)','موضوع تماس (Object) (Case)','علت وضعیت (Object) (Case)']}
];
const norm=(s:any)=>String(s??'').replace(/\.xlsx?$|\.xls$/i,'').replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[\u200c\u200f]/g,' ').replace(/\s+/g,' ').trim();
const hnorm=(s:any)=>norm(s).replace(/^\s+|\s+$/g,'');
const safeIdent=(s:string)=>/^[_a-zA-Z0-9]+$/.test(s)?`"${s}"`:(()=>{throw new Error('شناسه SQL نامعتبر است.')})();
function specFor(name:string){const n=norm(name);return SPECS.find(s=>n===norm(s.key))||null;}
function dateText(v:any){if(v==null||v==='')return '';if(v instanceof Date&&!isNaN(v.getTime()))return v.toISOString().replace('T',' ').slice(0,19);return String(v).trim();}
function num(v:any){if(v==null||v==='')return null;if(typeof v==='number')return v;const x=Number(String(v).replace(/[,٬]/g,''));return Number.isFinite(x)?x:null;}
function ageDays(v:any){const s=dateText(v);const d=new Date(s.includes('T')?s:s.replace(' ','T'));if(isNaN(d.getTime()))return null;return Math.max(0,Math.floor((Date.now()-d.getTime())/86400000));}
const H={
 team:{'نام و نام خانوادگی':'name','کد پرسنلی':'personnel_code','ایمیل شرکتی':'email','تیم لید':'team_lead','تیم':'team','جنسیت':'gender','رده':'role','واحد تجاری':'business_unit'},
 lead:{'شماره سرنخ':'lead_number','تاریخ ثبت':'created_date','رتبه مشتری (مشتری) (مشتری)':'customer_rank','تاریخ آخرین تغییر':'last_modified_date','آخرین وضعیت':'last_status','دلیل تماس بعدی':'next_call_reason','زمان پیگیری بعدی':'next_followup_at','نام مشتری':'customer_name',' نام مشتری':'customer_name','نام':'first_name','Middle Name':'middle_name','نام خانوادگی':'last_name','آخرین تغییر دهنده':'last_modified_by','ثبت کننده':'creator','مالک':'owner','نوع سرنخ':'lead_type','منشأ':'source','کمپین':'campaign','نرم افزار منشاء':'source_software','شناسه هویتی':'identity_id','تلفن همراه':'mobile','مشاور (مشتری) (مشتری)':'advisor','معرف (مشتری) (مشتری)':'referrer','جمع سرمایه گذاری واقعی (Base) (فرصت تجاری) (فرصت های تجاری)':'actual_investment','جمع سرمایه گذاری مورد انتظار (Base) (فرصت تجاری) (فرصت های تجاری)':'expected_investment','شهر (مشتری) (مشتری)':'city','واحد تجاری (Owning User) (کاربر)':'business_unit','Subject (تیکت منشأ) (Case)':'source_ticket_subject','موضوع تماس (تیکت منشأ) (Case)':'source_ticket_contact_topic'},
 opp:{'(Do Not Modify) Opportunity':'opportunity_id','عنوان':'title','تاریخ ثبت':'created_date','آخرین وضعیت':'last_status','وضعیت':'status','مشتری بالقوه':'potential_customer','منشا':'source','ثبت کننده':'creator','مالک':'owner','مرجع کمپین':'campaign_reference','منبع ورودی (سرنخ تجاری مربوطه) (سرنخ تجاری)':'input_source','کمپین (سرنخ تجاری مربوطه) (سرنخ تجاری)':'campaign','منشا تیکت':'ticket_source','نوع پرونده فروش':'sales_case_type','نوع سرمایه گذاری':'investment_type','جمع سرمایه گذاری مورد انتظار':'expected_investment','جمع سرمایه گذاری واقعی':'actual_investment','مشاور (مشتری بالقوه) (مشتری)':'advisor','معرف (مشتری بالقوه) (مشتری)':'referrer','منشأ (سرنخ تجاری مربوطه) (سرنخ تجاری)':'lead_source','نرم افزار منشاء (سرنخ تجاری مربوطه) (سرنخ تجاری)':'lead_source_software','واحد تجاری (Owning User) (کاربر)':'business_unit'},
 call:{'(Do Not Modify) Phone Call':'call_id','Subject':'subject','کاربر':'user','صف تماس':'queue','Start Date':'planned_start','Actual Start':'start_date','مشتری':'customer','رتبه مشتری (مشتری) (مشتری)':'customer_rank','شماره مقصد':'destination_number','Phone Number':'phone_number','پارامترها':'parameters','مدت تماس':'duration','واحد تجاری (کاربر) (کاربر)':'business_unit'},
 ticket:{'(Do Not Modify) Queue Item':'queue_item_id','Title':'title','موضوع تماس (Object) (Case)':'contact_topic','موضوع اصلی (Object) (Case)':'main_subject','Owner (Object) (Case)':'owner','Worked By':'worked_by','Resolve By (Object) (Case)':'resolve_by','Entered Queue':'entered_queue','علت وضعیت (Object) (Case)':'status_reason','رتبه مشتری (Object) (Case)':'customer_rank','Description (Object) (Case)':'description','Origin (Object) (Case)':'origin','Case Number (Object) (Case)':'case_number','کدملی (Object) (Case)':'national_id','Type':'type','زمان بسته شدن تیکت (Object) (Case)':'closed_at','Modified On':'modified_on','Modified By':'modified_by','Created On (Object) (Case)':'created_on','Created By':'created_by'}
} as Record<string,Record<string,string>>;
function readWorkbook(buffer:Buffer,fileName:string){const spec=specFor(fileName);if(!spec)throw new Error(`نام فایل شناخته نشد: ${fileName}`);const wb=XLSX.read(buffer,{type:'buffer',cellDates:true});const sheet=wb.SheetNames.find(n=>norm(n).includes(norm(spec.sheetIncludes)))||wb.SheetNames[0];if(!sheet)throw new Error('شیت قابل خواندن نیست.');const raw=XLSX.utils.sheet_to_json<any[]>(wb.Sheets[sheet],{header:1,defval:'',raw:true,blankrows:false});if(!raw.length)throw new Error('فایل خالی است.');const headers=(raw[0]||[]).map(hnorm);const missing=spec.required.filter(x=>!headers.includes(hnorm(x)));if(missing.length)throw new Error(`ستون‌های اجباری موجود نیست: ${missing.join('، ')}`);const map=H[spec.kind];const available=new Set<string>();for(const h of headers){const k=map[h];if(k)available.add(k)}if(spec.kind==='lead'&&spec.target==='open_leads')available.add('age_days');if(spec.kind==='opp')available.add('registration_type');if(spec.kind==='call')available.add('lead_number');if(spec.kind==='ticket')available.add('closed_at');const rows:any[]=[];for(const a of raw.slice(1)){if(!a||!a.some((v:any)=>v!==''&&v!=null))continue;const o:any={};headers.forEach((h:string,i:number)=>{const key=map[h];if(key)o[key]=a[i] instanceof Date?dateText(a[i]):a[i]});if(spec.kind==='lead'){o.created_date=dateText(o.created_date);o.last_modified_date=dateText(o.last_modified_date);if(spec.target==='open_leads')o.age_days=ageDays(o.created_date);o.actual_investment=num(o.actual_investment);o.expected_investment=num(o.expected_investment);}if(spec.kind==='opp'){o.created_date=dateText(o.created_date);const t=String(o.title||'').toUpperCase();o.registration_type=t.includes('-OPP-')?'OPP':t.includes('-LEAD-')?'LEAD':'';o.actual_investment=num(o.actual_investment);o.expected_investment=num(o.expected_investment);}if(spec.kind==='call'){o.start_date=dateText(o.start_date);o.planned_start=dateText(o.planned_start);const s=String(o.subject||'').toUpperCase();const m=s.match(/(?:LEAD|OPP)-\d+/);if(m)o.lead_number=m[0];}if(spec.kind==='ticket'){o.closed_at=dateText(o.closed_at)||dateText(o.modified_on);o.modified_on=dateText(o.modified_on);o.created_on=dateText(o.created_on);}rows.push(o);}return {spec,sheet,headers,rows,available:[...available]};}
async function tableColumns(table:string){const rows=await tursoSelect(`PRAGMA table_info(${safeIdent(table)})`);return (rows||[]).map((r:any)=>String(r.name));}
function pickColumns(available:string[],cols:string[]){const has=new Set(available);return cols.filter(c=>has.has(c));}
function placeholders(rows:number,cols:number){const one='('+Array(cols).fill('?').join(',')+')';return Array(rows).fill(one).join(',');}
export async function inspectExcel(buffer:Buffer,fileName:string){const p=readWorkbook(buffer,fileName);const dest=await tableColumns(p.spec.target);const insertCols=pickColumns(p.available,dest);return {file:fileName,dataset:p.spec.key,target:p.spec.target,sheet:p.sheet,rows:p.rows.length,columns:insertCols,mode:'replace'};}
export async function replaceExcel(buffer:Buffer,fileName:string){const p=readWorkbook(buffer,fileName);const target=p.spec.target,dest=await tableColumns(target);const cols=pickColumns(p.available,dest);if(!cols.length)throw new Error(`هیچ ستون قابل نگاشتی برای ${target} پیدا نشد.`);const stage=`stg_${target}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;const qstage=safeIdent(stage),qtarget=safeIdent(target),qcols=cols.map(safeIdent).join(',');try{await tursoBatch([{sql:`DROP TABLE IF EXISTS ${qstage}`},{sql:`CREATE TABLE ${qstage} AS SELECT * FROM ${qtarget} WHERE 0`}]);const chunk=600;for(let i=0;i<p.rows.length;i+=chunk){const part=p.rows.slice(i,i+chunk);const args:any[]=[];for(const r of part)for(const c of cols)args.push(r[c]===undefined?null:r[c]);await tursoBatch([{sql:`INSERT INTO ${qstage} (${qcols}) VALUES ${placeholders(part.length,cols.length)}`,args}]);}
 if(p.spec.kind==='call'&&dest.includes('lead_number')){const leadTable=target.replace(/calls$/,'leads');const lc=await tableColumns(leadTable).catch(()=>[]);if(lc.includes('identity_id')){const sourceCol=dest.includes('parameters')?'parameters':dest.includes('national_id')?'national_id':'';if(sourceCol)await tursoBatch([{sql:`UPDATE ${qstage} SET lead_number=(SELECT l.lead_number FROM ${safeIdent(leadTable)} l WHERE TRIM(COALESCE(l.identity_id,''))=TRIM(COALESCE(${qstage}.${safeIdent(sourceCol)},'')) LIMIT 1) WHERE TRIM(COALESCE(lead_number,''))='' AND TRIM(COALESCE(${safeIdent(sourceCol)},''))<>''`}]);}}
 const version=`${Date.now()}-${Math.floor(Math.random()*100000)}`,now=new Date().toISOString();await tursoBatch([{sql:'BEGIN IMMEDIATE'},{sql:`DELETE FROM ${qtarget}`},{sql:`INSERT INTO ${qtarget} (${qcols}) SELECT ${qcols} FROM ${qstage}`},{sql:`DROP TABLE ${qstage}`},{sql:"INSERT INTO dashboard_meta(key,value) VALUES('data_version',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",args:[version]},{sql:"INSERT INTO dashboard_meta(key,value) VALUES('last_sync_at',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",args:[now]},{sql:'COMMIT'}]);return {file:fileName,dataset:p.spec.key,target,rows:p.rows.length,columns:cols,dataVersion:version,lastSyncAt:now,mode:'replace'};}catch(e){await tursoBatch([{sql:`DROP TABLE IF EXISTS ${qstage}`}]).catch(()=>{});throw e;}}
